Portfolio
AbdifatahYasin1/My-portfolio-Web pull request #2
Opened 2022-09-20 14:58 UTC by AbdifatahYasin1

# Portfolio Page

This is portfolio page designed by Abdifatah

2022-09-20 16:20 UTC, Qoosim requested changes
#   *Status: Required Changes* :recycle: 

Hi @AbdifatahYasin1, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

-   No linter errors. :heavy_check_mark:
-   Good README file. :heavy_check_mark: 
-   Correct GitHub Flow. :heavy_check_mark: 
-   meaningful commit messages. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-20 16:20 UTC, Qoosim commented on index.html
> +      <div class="workd-card about-myself">
- [ ] Kindly make this `section` tag instead of ordinary `div` for semantic reasons.

2022-09-20 16:20 UTC, Qoosim commented on index.html
> +        <p id="text-color">LET’S CONNECT</p>
- [ ] Kindly make this `hx` tag. It could be `h2, h3, h4, ....` instead of `p` tag for sematic reason.

2022-09-20 16:20 UTC, Qoosim commented on index.html
> +
- [ ] It is highly recommended to make social icon as a link for sematic reason and accessibility purpose. Kindly use `<li><a>Your icon</a></li>` for all your social icons.

2022-09-20 16:20 UTC, Qoosim commented on style.css
> +}
- [ ] Kindly give your button for `Get my resume` the button styling like Active, Hover and Pressed (see design). This is highly recommended for semantic reason.

2022-09-20 16:20 UTC, Qoosim commented on index.html
> +      </div>
- [ ] All the technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li`. Kindly look into this and refactor your code.

2022-09-21 08:47 UTC, franclobo reviewed
Hi @AbdifatahYasin1, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't correspond with the activity in the dashboard, it appears as "Portfolio: finish mobile version", but it is about the first part of the portfolio.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-21 09:46 UTC, Ugboaja-Uchechi approved these changes
Hi @AbdifatahYasin1 , 

## Status: APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 
- Great job with your design and functionalities 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 09:48 UTC, topeogunleye reviewed
Hi @AbdifatahYasin1, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a project with an old pull request. Each project should have a separate Pull Request.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

2022-10-01 08:00 UTC, merged